import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Container, Row } from "react-bootstrap";
import styles from "../styles/pages/index.module.scss";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>My Blog Site</title>
        <meta name="description" content="Generated by create next app" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="apple-mobile-web-app-title" content="Ilshaad blog" />
        <meta name="application-name" content="Ilshaad blog" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <h2>iK put a slogon of some sort here</h2>

      <h4>Latest</h4>

      {/* blog post collection list */}
      <Container fluid as="ul">
        {/* /blog/1 */}
        <Row as="li" className="bg-light">
          <h5>blog title</h5>

          <p className={styles.index_page_blogPostSample}>
            describe the post but not finish it, write a click me bait under it
            with read more button. I am just adding more to it to increase the
            word counts. I do not know how lines is suffiecient enough. Perhaps
            I is should use three lines base on what I am seeing
          </p>

          <Link href="/blog/1">Read more&rarr;</Link>

          <time dateTime="2022-06-25" className="d-block">
            2022 June 25th Friday
          </time>
        </Row>

        {/* /blog/2 */}
        <Row as="li" className="bg-light">
          <h5>blog title</h5>

          <p className={styles.index_page_blogPostSample}>
            describe the post but not finish it, write a click me bait under it
            with read more button. I am just adding more to it to increase the
            word counts. I do not know how lines is suffiecient enough. Perhaps
            I is should use three lines base on what I am seeing
          </p>

          <Link href="/blog/1">Read more&rarr;</Link>

          <time dateTime="2022-06-25" className="d-block">
            2022 June 25th Friday
          </time>
        </Row>
      </Container>
    </Container>
  );
};

export default Home;
